# Use ubuntu trusty (14.04) with sudo privileges.
dist: trusty
sudo: required
language:
  - generic
cache:
  - apt
env:

before_install:
  - export CI_SOURCE_PATH=$(pwd)
install:
  - bash .env
before_script:
script:
  - ./test.sh